spring:
  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35
  instance:
    preferIpAddress: true