server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: client-service
  cloud:
    config:
      enabled: false
  zipkin:
    enabled: true


feign:
  circuit breaker:
    enabled: true

Lospring:
  sleuth:
    sampler:
      probability: 2.0

logging:
  file:
    name: c:\Users\wertor\logs\application.log