server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: creation-book-service
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        bookEventProcessor-out-0:
          destination: create-book