server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      enabled: true
  profiles:
    active: native
  data:
    mongodb:
    database: admin
    username: admin
    password: admin