spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetchRegistry: false
    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    use-dns-for-fetching-service-urls: false
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    registerWithEureka: false
    log-delta-diff: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    should-unregister-on-shutdown: true
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 70
